version: "3.9"
services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      POSTGRES_DB: "dictionaries"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test -d dictionaries" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s